name: NASA Project CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  env:
     CI: true 
  strategy:
    matrix:
      node-version: [14.x, 16.x]   
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@2
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install
      - run: cd nasa-frontend && npm run build
      -run: npm test